In [66]:
import pandas as pd

df = pd.read_csv("Dataset .csv")

df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [67]:
chain_counts = df['Restaurant Name'].value_counts()

chains = chain_counts[chain_counts > 1]

chains.head(10)

Restaurant Name
Cafe Coffee Day     83
Domino's Pizza      79
Subway              63
Green Chick Chop    51
McDonald's          48
Keventers           34
Pizza Hut           30
Giani               29
Baskin Robbins      28
Barbeque Nation     26
Name: count, dtype: int64

In [68]:
top_chains = chains.sort_values(ascending=False).head(10)

top_chains

Restaurant Name
Cafe Coffee Day     83
Domino's Pizza      79
Subway              63
Green Chick Chop    51
McDonald's          48
Keventers           34
Pizza Hut           30
Giani               29
Baskin Robbins      28
Barbeque Nation     26
Name: count, dtype: int64

In [69]:
chain_ratings = df[df['Restaurant Name'].isin(top_chains.index)]

avg_chain_rating = chain_ratings.groupby('Restaurant Name')['Aggregate rating'].mean()

avg_chain_rating.sort_values(ascending=False)

Restaurant Name
Barbeque Nation     4.353846
McDonald's          3.339583
Pizza Hut           3.320000
Subway              2.907937
Keventers           2.870588
Domino's Pizza      2.740506
Giani               2.689655
Green Chick Chop    2.672549
Cafe Coffee Day     2.419277
Baskin Robbins      1.860714
Name: Aggregate rating, dtype: float64

In [70]:
chain_votes = chain_ratings.groupby('Restaurant Name')['Votes'].mean()

chain_votes.sort_values(ascending=False)

Restaurant Name
Barbeque Nation     1082.384615
Pizza Hut            165.366667
McDonald's           110.229167
Subway                97.206349
Domino's Pizza        84.088608
Keventers             37.147059
Giani                 29.448276
Cafe Coffee Day       29.253012
Green Chick Chop      18.901961
Baskin Robbins        15.285714
Name: Votes, dtype: float64

In [72]:
print("Top Restaurant Chains:\n", top_chains)

print("\nAverage Ratings of Chains:\n", avg_chain_rating.round(2))

print("\nAverage Votes (Popularity):\n", chain_votes.round(2))

Top Restaurant Chains:
 Restaurant Name
Cafe Coffee Day     83
Domino's Pizza      79
Subway              63
Green Chick Chop    51
McDonald's          48
Keventers           34
Pizza Hut           30
Giani               29
Baskin Robbins      28
Barbeque Nation     26
Name: count, dtype: int64

Average Ratings of Chains:
 Restaurant Name
Barbeque Nation     4.35
Baskin Robbins      1.86
Cafe Coffee Day     2.42
Domino's Pizza      2.74
Giani               2.69
Green Chick Chop    2.67
Keventers           2.87
McDonald's          3.34
Pizza Hut           3.32
Subway              2.91
Name: Aggregate rating, dtype: float64

Average Votes (Popularity):
 Restaurant Name
Barbeque Nation     1082.38
Baskin Robbins        15.29
Cafe Coffee Day       29.25
Domino's Pizza        84.09
Giani                 29.45
Green Chick Chop      18.90
Keventers             37.15
McDonald's           110.23
Pizza Hut            165.37
Subway                97.21
Name: Votes, dtype: float64